# Generated by Django 4.2.1 on 2023-09-29 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistry',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractbasemodel')),
                ('company_name', models.CharField(max_length=250)),
                ('vat_number', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'unique_together': {('company_name', 'vat_number')},
            },
            bases=('core.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='DocumentCustomer',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractbasemodel')),
                ('date', models.DateField()),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(editable=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerregistry')),
            ],
            options={
                'unique_together': {('year', 'number')},
            },
            bases=('core.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='DocumentFromSupplier',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractbasemodel')),
                ('date', models.DateField()),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(editable=False)),
            ],
            bases=('core.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='DocumentToSupplier',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractbasemodel')),
                ('date', models.DateField()),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(editable=False)),
            ],
            bases=('core.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='WarehouseItemsRegistry',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractbasemodel')),
                ('description', models.CharField(max_length=250)),
                ('external_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('internal_code', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            bases=('core.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='WarehouseItems',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractbasemodel')),
                ('status', models.CharField(blank=True, choices=[('A', 'Available'), ('B', 'Booked'), ('E', 'Empty'), ('R', 'Returned')], default=None, max_length=1, null=True)),
                ('empty_date', models.DateField(blank=True, db_index=True, null=True)),
                ('batch_code', models.CharField(db_index=True, max_length=100)),
                ('document_customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_customer', to='core.documentcustomer')),
                ('document_from_supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_from_supplier', to='core.documentfromsupplier')),
                ('document_to_supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_to_supplier', to='core.documenttosupplier')),
            ],
            bases=('core.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='SupplierRegistry',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractbasemodel')),
                ('company_name', models.CharField(max_length=250)),
                ('vat_number', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'unique_together': {('company_name', 'vat_number')},
            },
            bases=('core.abstractbasemodel',),
        ),
        migrations.AddField(
            model_name='documenttosupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplierregistry'),
        ),
        migrations.AddField(
            model_name='documentfromsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplierregistry'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttosupplier',
            unique_together={('year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='documentfromsupplier',
            unique_together={('year', 'number')},
        ),
    ]
