# Generated by Django 4.2.1 on 2024-02-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_documentcustomer_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitems",
            name="document_customer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_items",
                to="core.documentcustomer",
            ),
        ),
    ]
