name: Generate deploy server on release

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Build React app
        run: | 
          npm run build
          npm run twbuild
          python django/manage.py collectstatic --no-input

      - name: Remove unwanted files and folders
        run: |
          rm -rf node_modules
          rm -rf react_app
          rm -rf README.md
          rm -rf .prettierrc
          rm -rf postman.postman_collection.json
          rm -rf django/webpack-stats.json
          rm -rf package.json
          rm -rf .babelrc
          rm -rf .gitignore
          rm -rf webpack.config.js
          rm -rf package-lock.json
          rm -rf tailwind.config.js
          rm -rf .github
          rm -rf .git
          rm -rf django/tailwind.css
          rm -rf django/docker

      - name: Create release archive
        run: |
          zip -r release_files.zip .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release_files.zip
          asset_name: release_files.zip
          asset_content_type: application/zip
